services:
  
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: movie_goer
    ports:
      - "5433:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db 
      DB_PORT: 5432
      DB_USER: docker_user
      DB_PASSWORD: docker_password
      DB_NAME: movie_goer
      JWT_SECRET: super_secret_production_key
    depends_on:
      - db 


volumes:
  pgdata: